sudo: false
cache: bundler
language: ruby

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2

before_install:
  - gem update --system
  - gem install bundler
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
